# Generated by Django 5.0.1 on 2024-02-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_footeritem_alter_dish_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery/')),
                ('tittle', models.CharField(blank=True, max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
