# Generated by Django 5.0.1 on 2024-02-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_reservation_alter_gallery_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='massage',
            new_name='message',
        ),
    ]
