# Generated by Django 5.0.1 on 2024-02-23 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_massage_reservation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+380xxxxxxxxx'.", regex='^\\+?380\\d{9}$')]),
        ),
    ]
