# Generated by Django 5.0.1 on 2024-02-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_chefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefs',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
