# Generated by Django 5.0.1 on 2024-02-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='tittle',
            new_name='name',
        ),
    ]
